name: Workflow-2

on:
  workflow_run:
    workflows: ["Workflow-1"]
    types:
      - completed

jobs:
  check-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check individual job statuses
        run: |
          workflow_run_id="${{ github.event.workflow_run.id }}"
          repo="${{ github.repository }}"
          jobs=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$repo/actions/runs/$workflow_run_id/jobs")

          # Check each job's conclusion
          for job in $(echo "$jobs" | jq -r '.jobs[] | .conclusion'); do
            if [ "$job" != "success" ]; then
              echo "Workflow-1 job did not succeed. Skipping Workflow-2."
              exit 78  # exit with a neutral status
            fi
          done

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Triggered by Workflow-1 completion
        run: echo "Workflow-2 triggered by Workflow-1 completion"

      # Add more steps as needed
