name: Workflow-1

on:
  pull_request:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: | 
          echo "Running step 1 in Workflow 1"
          exit 1

      # Add more steps as needed

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Step 2
        run: | 
          echo "Running step 2 in Workflow 1"


      # Add more steps as needed
      - name: Check if Workflow-1 was successful
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
            echo "Workflow-2 triggered by Workflow-1 completion"
          else
            echo "Workflow-1 did not succeed. Skipping Workflow-2."
            exit 78  # exit with a neutral status
          fi
