name: Workflow-2

on:
  workflow_run:
    workflows: ["Workflow-1"]
    types:
      - completed
 

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: need to get the branch
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.workflow_run.head_branch}}

      - name: Triggered by Workflow 1 completion
        run: echo "Workflow 2 triggered by Workflow 1 completion"

      # Add more steps as needed
      - name: Check if Workflow-1 was successful
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
            echo "Workflow-2 triggered by Workflow-1 completion"
          else
            echo "Workflow-1 did not succeed. Skipping Workflow-2."
            exit 78  # exit with a neutral status
          fi
