name: Workflow-2

on:
  pull_request:
    branches:
      - master

jobs:
  check-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Workflow-1 completion
        uses: softprops/action-workflow-run@v1
        with:
          workflow: "Workflow-1"
          wait-for-status: success

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Triggered by Workflow-1 completion
        run: echo "Workflow-2 triggered by Workflow-1 completion"

      # Add more steps as needed
